### ISSUE TITLE
Publish new version to pypy

### ISSUE THREAD

**Issue by marcosfelt** [ssanderson/interface#19]
First off, great package!

There are some recent features such as `Interface.from_class()` that justify publishing a new version to pypy.  It looks like the pypy distribution hasn't been updated since December 2017.

**Comment by ssanderson** [comment]
:+1: I'll try to push out a new release some time this week.

**Comment by marcosfelt** [comment]
Sounds good!

**Comment by ssanderson** [comment]
Just released 1.5.0. https://github.com/ssanderson/interface/releases/tag/1.5.0.
