### ISSUE TITLE
Does Interface work with Python 3.6 & 3.7

### ISSUE THREAD

**Issue by ReblochonMasque** [ssanderson/interface#25]
Hello Scott,

The docs & readme mention python 2.7 & 3.4; does Interface work with python 3.6 & 3.7?

Thank you
Cheers

**Comment by ssanderson** [comment]
Yes. We support 2.7 and 3.4 or greater.

**Comment by ReblochonMasque** [comment]
Good to know, thank you for your reply Scott.
Would you like me to amend the docs and readme to reflect this and make it explicitly clear (I think it should be done), and post a pull request for it?
