### ISSUE TITLE
Working with interfaces in separate files not working?

### ISSUE THREAD

**Issue by nagreme** [ssanderson/interface#30]
I've implemented an interface in one file let's call it A.py:
```python
from interface import Interface

class A(Interface):
  def method1(self):
    pass
```

And when I try to import and use it in another file, say B.py:
```python
from interface import implements
import A

class B(implements(A)):
  def method1(self):
    print("foo")

b = B()
b.method1()
```

When I run B.py or whenever I try to import B I get this error:
```
Traceback (most recent call last):
  File "B.py", line 4, in <module>
    class B(implements(A)):
  File "/home/nagreme/.local/lib/python3.6/site-packages/interface/interface.py", line 490, in implements
    if not issubclass(I, Interface):
TypeError: issubclass() arg 1 must be a class
```

If I put the implementation of A in the same file it works but that isn't really convenient for bigger projects with several more complex implementing classes: is there any way to fix this or work around it?

**Comment by ssanderson** [comment]
@nagreme your `import A` line is giving you the `module` object defined by `A.py`, not the `A` interface defined within that module. 

You want to change your second example to something like:

```python
from interface import implements
from A import A

class B(implements(A)):
  def method1(self):
    print("foo")

b = B()
b.method1()
```

or, equivalently

```
from interface import implements
import A  # A is the A.py module

class B(implements(A.A)):  # A.A is the A class that's part of the module.
  def method1(self):
    print("foo")

b = B()
b.method1()
```

**Comment by nagreme** [comment]
Ah oops I just realized that! Thank you for your response, this is a great project!
